// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/jkuri/abstruse/internal/pkg/config"
	"github.com/jkuri/abstruse/internal/pkg/log"
	"github.com/jkuri/abstruse/internal/worker"
	"github.com/jkuri/abstruse/internal/worker/etcd"
	"github.com/jkuri/abstruse/internal/worker/grpc"
	"github.com/jkuri/abstruse/internal/worker/scheduler"
)

// Injectors from wire.go:

func CreateApp(cfg string) (*worker.App, error) {
	viper, err := config.NewConfig(cfg)
	if err != nil {
		return nil, err
	}
	options, err := worker.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logOptions, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(logOptions)
	if err != nil {
		return nil, err
	}
	grpcOptions, err := grpc.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	etcdOptions, err := etcd.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	app := etcd.NewApp(etcdOptions, logger)
	schedulerOptions, err := scheduler.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	schedulerScheduler := scheduler.NewScheduler(schedulerOptions, logger)
	server, err := grpc.NewServer(grpcOptions, logger, app, schedulerScheduler)
	if err != nil {
		return nil, err
	}
	workerApp := worker.NewApp(options, logger, server, app)
	return workerApp, nil
}

// wire.go:

var providerSet = wire.NewSet(log.ProviderSet, config.ProviderSet, grpc.ProviderSet, worker.ProviderSet, etcd.ProviderSet, scheduler.ProviderSet)
