language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: NODE_SCRIPT=./tests/run_e2e.js
  - node_js: "8"
    env: SCRIPT=protractor:abstruse

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install
  - sudo apt-get install -y docker.io sqlite3

postinstall:
  - sudo usermod -aG docker abstruse
  - sudo /etc/init.d/docker start
  - sudo /etc/init.d/xvfb start

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node ./$NODE_SCRIPT; fi
