language: node_js

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test
  - node_js: "8"
    env: SCRIPT=test:e2e
  - node_js: "8"
    env: SCRIPT=test:protractor
  - node_js: "8"
    env: SCRIPT=cli

before_install:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

before_script:
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  directories:
    - node_modules
