language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: NODE_SCRIPT=./tests/run_e2e.js
  - node_js: "8"
    env: SCRIPT=protractor:abstruse

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce sqlite3 -y

postinstall:
  - sudo usermod -aG docker abstruse
  - sudo /etc/init.d/docker start
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node ./$NODE_SCRIPT; fi
