language: node_js

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test
  - node_js: "8"
    env: SCRIPT=test:e2e
  - node_js: "8"
    env: SCRIPT=test:protractor
  - node_js: "8"
    env: SCRIPT=cli

before_install:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install
  - sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
  - sudo apt-get update && sudo apt-get install -y docker-ce sqlite3

before_script:
  - sudo usermod -aG docker abstruse
  - sudo /etc/init.d/docker start
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  directories:
    - node_modules

