language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: NODE_SCRIPT=./tests/run_e2e.js
  - node_js: "8"
    env: SCRIPT=protractor:abstruse

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install
  - curl -fsSL get.docker.com -o get-docker.sh
  - chmod +x get-docker.sh
  - sudo ./get-docker.sh
  - sudo apt-get install sqlite3 -y
  - sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual -y

postinstall:
  - sudo $(which node) ./tests/postinstall_ci.js
  - sudo usermod -aG docker abstruse
  - sudo /etc/init.d/docker start
  - sudo /etc/init.d/xvfb start
  - export DISPLAY=:99

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node ./$NODE_SCRIPT; fi
