language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: NODE_SCRIPT=./tests/run_e2e.js

preinstall:
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

postinstall:
  - npm install enhanced-resolve@3.3.0 webpack@3.3.0

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
  - if [[ "$NODE_SCRIPT" ]]; then node ./$NODE_SCRIPT; fi
