image: abstruse

matrix:
  - env: SCRIPT=lint NODE_VERSION=8
  - env: SCRIPT=test NODE_VERSION=8
  - env: SCRIPT=test:e2e NODE_VERSION=8
  - env: SCRIPT=test:protractor NODE_VERSION=8

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

cache:
  - node_modules
