# stage 1 build
FROM golang:1.11-alpine as build

WORKDIR /app

RUN apk --no-cache add git make protobuf protobuf-dev ca-certificates

COPY . /app/

RUN go get github.com/jteeuwen/go-bindata/... github.com/golang/protobuf/protoc-gen-go

RUN make grpc && make worker

# stage 2 image
FROM scratch

COPY --from=build /etc/ssl/certs /etc/ssl/certs
COPY --from=build /app/build/abstruse-worker /usr/bin/abstruse-worker

ENTRYPOINT [ "/usr/bin/abstruse-worker" ]

EXPOSE 80 443
