export let request = {
  'action': 'created',
  'issue': {
    'url': 'https://api.github.com/repos/bleenco/morose/issues/87',
    'repository_url': 'https://api.github.com/repos/bleenco/morose',
    'labels_url': 'https://api.github.com/repos/bleenco/morose/issues/87/labels{/name}',
    'comments_url': 'https://api.github.com/repos/bleenco/morose/issues/87/comments',
    'events_url': 'https://api.github.com/repos/bleenco/morose/issues/87/events',
    'html_url': 'https://github.com/bleenco/morose/pull/87',
    'id': 245639606,
    'number': 87,
    'title': 'test',
    'user': {
      'login': 'Izak88',
      'id': 8555269,
      'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/Izak88',
      'html_url': 'https://github.com/Izak88',
      'followers_url': 'https://api.github.com/users/Izak88/followers',
      'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
      'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
      'organizations_url': 'https://api.github.com/users/Izak88/orgs',
      'repos_url': 'https://api.github.com/users/Izak88/repos',
      'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/Izak88/received_events',
      'type': 'User',
      'site_admin': false
    },
    'labels': [
      {
        'id': 597303867,
        'url': 'https://api.github.com/repos/bleenco/morose/labels/Status:%20Abandoned',
        'name': 'Status: Abandoned',
        'color': '000000',
        'default': false
      }
    ],
    'state': 'open',
    'locked': false,
    'assignee': null,
    'assignees': [

    ],
    'milestone': null,
    'comments': 1,
    'created_at': '2017-07-26T08:09:26Z',
    'updated_at': '2017-07-26T10:27:28Z',
    'closed_at': null,
    'pull_request': {
      'url': 'https://api.github.com/repos/bleenco/morose/pulls/87',
      'html_url': 'https://github.com/bleenco/morose/pull/87',
      'diff_url': 'https://github.com/bleenco/morose/pull/87.diff',
      'patch_url': 'https://github.com/bleenco/morose/pull/87.patch'
    },
    'body': ''
  },
  'comment': {
    'url': 'https://api.github.com/repos/bleenco/morose/issues/comments/318014394',
    'html_url': 'https://github.com/bleenco/morose/pull/87#issuecomment-318014394',
    'issue_url': 'https://api.github.com/repos/bleenco/morose/issues/87',
    'id': 318014394,
    'user': {
      'login': 'Izak88',
      'id': 8555269,
      'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/Izak88',
      'html_url': 'https://github.com/Izak88',
      'followers_url': 'https://api.github.com/users/Izak88/followers',
      'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
      'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
      'organizations_url': 'https://api.github.com/users/Izak88/orgs',
      'repos_url': 'https://api.github.com/users/Izak88/repos',
      'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/Izak88/received_events',
      'type': 'User',
      'site_admin': false
    },
    'created_at': '2017-07-26T10:27:28Z',
    'updated_at': '2017-07-26T10:27:28Z',
    'body': 'test comment'
  },
  'repository': {
    'id': 72294758,
    'name': 'morose',
    'full_name': 'bleenco/morose',
    'owner': {
      'login': 'bleenco',
      'id': 26046537,
      'avatar_url': 'https://avatars2.githubusercontent.com/u/26046537?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/bleenco',
      'html_url': 'https://github.com/bleenco',
      'followers_url': 'https://api.github.com/users/bleenco/followers',
      'following_url': 'https://api.github.com/users/bleenco/following{/other_user}',
      'gists_url': 'https://api.github.com/users/bleenco/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/bleenco/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/bleenco/subscriptions',
      'organizations_url': 'https://api.github.com/users/bleenco/orgs',
      'repos_url': 'https://api.github.com/users/bleenco/repos',
      'events_url': 'https://api.github.com/users/bleenco/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/bleenco/received_events',
      'type': 'Organization',
      'site_admin': false
    },
    'private': false,
    'html_url': 'https://github.com/bleenco/morose',
    'description': '📦  private npm repository and/or proxy server for npmjs.org',
    'fork': false,
    'url': 'https://api.github.com/repos/bleenco/morose',
    'forks_url': 'https://api.github.com/repos/bleenco/morose/forks',
    'keys_url': 'https://api.github.com/repos/bleenco/morose/keys{/key_id}',
    'collaborators_url': 'https://api.github.com/repos/bleenco/morose/collaborators{/collaborator}',
    'teams_url': 'https://api.github.com/repos/bleenco/morose/teams',
    'hooks_url': 'https://api.github.com/repos/bleenco/morose/hooks',
    'issue_events_url': 'https://api.github.com/repos/bleenco/morose/issues/events{/number}',
    'events_url': 'https://api.github.com/repos/bleenco/morose/events',
    'assignees_url': 'https://api.github.com/repos/bleenco/morose/assignees{/user}',
    'branches_url': 'https://api.github.com/repos/bleenco/morose/branches{/branch}',
    'tags_url': 'https://api.github.com/repos/bleenco/morose/tags',
    'blobs_url': 'https://api.github.com/repos/bleenco/morose/git/blobs{/sha}',
    'git_tags_url': 'https://api.github.com/repos/bleenco/morose/git/tags{/sha}',
    'git_refs_url': 'https://api.github.com/repos/bleenco/morose/git/refs{/sha}',
    'trees_url': 'https://api.github.com/repos/bleenco/morose/git/trees{/sha}',
    'statuses_url': 'https://api.github.com/repos/bleenco/morose/statuses/{sha}',
    'languages_url': 'https://api.github.com/repos/bleenco/morose/languages',
    'stargazers_url': 'https://api.github.com/repos/bleenco/morose/stargazers',
    'contributors_url': 'https://api.github.com/repos/bleenco/morose/contributors',
    'subscribers_url': 'https://api.github.com/repos/bleenco/morose/subscribers',
    'subscription_url': 'https://api.github.com/repos/bleenco/morose/subscription',
    'commits_url': 'https://api.github.com/repos/bleenco/morose/commits{/sha}',
    'git_commits_url': 'https://api.github.com/repos/bleenco/morose/git/commits{/sha}',
    'comments_url': 'https://api.github.com/repos/bleenco/morose/comments{/number}',
    'issue_comment_url': 'https://api.github.com/repos/bleenco/morose/issues/comments{/number}',
    'contents_url': 'https://api.github.com/repos/bleenco/morose/contents/{+path}',
    'compare_url': 'https://api.github.com/repos/bleenco/morose/compare/{base}...{head}',
    'merges_url': 'https://api.github.com/repos/bleenco/morose/merges',
    'archive_url': 'https://api.github.com/repos/bleenco/morose/{archive_format}{/ref}',
    'downloads_url': 'https://api.github.com/repos/bleenco/morose/downloads',
    'issues_url': 'https://api.github.com/repos/bleenco/morose/issues{/number}',
    'pulls_url': 'https://api.github.com/repos/bleenco/morose/pulls{/number}',
    'milestones_url': 'https://api.github.com/repos/bleenco/morose/milestones{/number}',
    'notifications_url':
      'https://api.github.com/repos/bleenco/morose/notifications{?since,all,participating}',
    'labels_url': 'https://api.github.com/repos/bleenco/morose/labels{/name}',
    'releases_url': 'https://api.github.com/repos/bleenco/morose/releases{/id}',
    'deployments_url': 'https://api.github.com/repos/bleenco/morose/deployments',
    'created_at': '2016-10-29T16:02:28Z',
    'updated_at': '2017-06-23T00:20:33Z',
    'pushed_at': '2017-07-26T08:09:27Z',
    'git_url': 'git://github.com/bleenco/morose.git',
    'ssh_url': 'git@github.com:bleenco/morose.git',
    'clone_url': 'https://github.com/bleenco/morose.git',
    'svn_url': 'https://github.com/bleenco/morose',
    'homepage': 'https://morose.bleenco.io',
    'size': 1990,
    'stargazers_count': 12,
    'watchers_count': 12,
    'language': 'TypeScript',
    'has_issues': true,
    'has_projects': true,
    'has_downloads': true,
    'has_wiki': true,
    'has_pages': false,
    'forks_count': 3,
    'mirror_url': null,
    'open_issues_count': 2,
    'forks': 3,
    'open_issues': 2,
    'watchers': 12,
    'default_branch': 'master'
  },
  'organization': {
    'login': 'bleenco',
    'id': 26046537,
    'url': 'https://api.github.com/orgs/bleenco',
    'repos_url': 'https://api.github.com/orgs/bleenco/repos',
    'events_url': 'https://api.github.com/orgs/bleenco/events',
    'hooks_url': 'https://api.github.com/orgs/bleenco/hooks',
    'issues_url': 'https://api.github.com/orgs/bleenco/issues',
    'members_url': 'https://api.github.com/orgs/bleenco/members{/member}',
    'public_members_url': 'https://api.github.com/orgs/bleenco/public_members{/member}',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/26046537?v=4',
    'description': ''
  },
  'sender': {
    'login': 'Izak88',
    'id': 8555269,
    'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/Izak88',
    'html_url': 'https://github.com/Izak88',
    'followers_url': 'https://api.github.com/users/Izak88/followers',
    'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
    'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
    'organizations_url': 'https://api.github.com/users/Izak88/orgs',
    'repos_url': 'https://api.github.com/users/Izak88/repos',
    'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/Izak88/received_events',
    'type': 'User',
    'site_admin': false
  }
};

export let header = {
  'content-type': 'application/json',
  'X-GitHub-Event': 'issue_comment',
  'X-Hub-Signature': 'sha1=b7c49c4f28d64c153ae1ab7f7a8627a1f66a9e55',
  'X-GitHub-Delivery': '61109660-71f6-11e7-9b49-619c5e386bdf'
};
