export let request = {
  'id': 1408206276,
  'sha': '968d81824597bbaebad9bd22e0d15fb4e04d2077',
  'name': 'bleenco/morose',
  'target_url': 'https://travis-ci.org/bleenco/morose/builds/'
                + '257626820?utm_source=github_status&utm_medium=notification',
  'context': 'continuous-integration/travis-ci/pr',
  'description': 'The Travis CI build failed',
  'state': 'failure',
  'commit': {
    'sha': '968d81824597bbaebad9bd22e0d15fb4e04d2077',
    'commit': {
      'author': {
        'name': 'Izak Lipnik',
        'email': 'izak.lipnik@gmail.com',
        'date': '2017-07-26T08:08:26Z'
      },
      'committer': {
        'name': 'Izak Lipnik',
        'email': 'izak.lipnik@gmail.com',
        'date': '2017-07-26T08:08:49Z'
      },
      'message': 'test',
      'tree': {
        'sha': 'a11b78d47bf7486634ca208c4a2f7505f66f8d7e',
        'url': 'https://api.github.com/repos/bleenco/morose/'
               + 'git/trees/a11b78d47bf7486634ca208c4a2f7505f66f8d7e'
      },
      'url': 'https://api.github.com/repos/bleenco/morose/git'
             + '/commits/968d81824597bbaebad9bd22e0d15fb4e04d2077',
      'comment_count': 0
    },
    'url': 'https://api.github.com/repos/bleenco/morose'
           + '/commits/968d81824597bbaebad9bd22e0d15fb4e04d2077',
    'html_url': 'https://github.com/bleenco/morose/commit/968d81824597bbaebad9bd22e0d15fb4e04d2077',
    'comments_url': 'https://api.github.com/repos/bleenco/morose'
                    + '/commits/968d81824597bbaebad9bd22e0d15fb4e04d2077/comments',
    'author': {
      'login': 'Izak88',
      'id': 8555269,
      'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/Izak88',
      'html_url': 'https://github.com/Izak88',
      'followers_url': 'https://api.github.com/users/Izak88/followers',
      'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
      'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
      'organizations_url': 'https://api.github.com/users/Izak88/orgs',
      'repos_url': 'https://api.github.com/users/Izak88/repos',
      'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/Izak88/received_events',
      'type': 'User',
      'site_admin': false
    },
    'committer': {
      'login': 'Izak88',
      'id': 8555269,
      'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/Izak88',
      'html_url': 'https://github.com/Izak88',
      'followers_url': 'https://api.github.com/users/Izak88/followers',
      'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
      'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
      'organizations_url': 'https://api.github.com/users/Izak88/orgs',
      'repos_url': 'https://api.github.com/users/Izak88/repos',
      'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/Izak88/received_events',
      'type': 'User',
      'site_admin': false
    },
    'parents': [
      {
        'sha': '1ced7484acaeeb479f2ecb838446b3dfade41abb',
        'url': 'https://api.github.com/repos/bleenco/morose'
              + '/commits/1ced7484acaeeb479f2ecb838446b3dfade41abb',
        'html_url': 'https://github.com/bleenco/morose/commit'
                    + '/1ced7484acaeeb479f2ecb838446b3dfade41abb'
      }
    ]
  },
  'branches': [

  ],
  'created_at': '2017-07-26T08:24:02Z',
  'updated_at': '2017-07-26T08:24:02Z',
  'repository': {
    'id': 72294758,
    'name': 'morose',
    'full_name': 'bleenco/morose',
    'owner': {
      'login': 'bleenco',
      'id': 26046537,
      'avatar_url': 'https://avatars2.githubusercontent.com/u/26046537?v=4',
      'gravatar_id': '',
      'url': 'https://api.github.com/users/bleenco',
      'html_url': 'https://github.com/bleenco',
      'followers_url': 'https://api.github.com/users/bleenco/followers',
      'following_url': 'https://api.github.com/users/bleenco/following{/other_user}',
      'gists_url': 'https://api.github.com/users/bleenco/gists{/gist_id}',
      'starred_url': 'https://api.github.com/users/bleenco/starred{/owner}{/repo}',
      'subscriptions_url': 'https://api.github.com/users/bleenco/subscriptions',
      'organizations_url': 'https://api.github.com/users/bleenco/orgs',
      'repos_url': 'https://api.github.com/users/bleenco/repos',
      'events_url': 'https://api.github.com/users/bleenco/events{/privacy}',
      'received_events_url': 'https://api.github.com/users/bleenco/received_events',
      'type': 'Organization',
      'site_admin': false
    },
    'private': false,
    'html_url': 'https://github.com/bleenco/morose',
    'description': '📦  private npm repository and/or proxy server for npmjs.org',
    'fork': false,
    'url': 'https://api.github.com/repos/bleenco/morose',
    'forks_url': 'https://api.github.com/repos/bleenco/morose/forks',
    'keys_url': 'https://api.github.com/repos/bleenco/morose/keys{/key_id}',
    'collaborators_url': 'https://api.github.com/repos/bleenco/morose/collaborators{/collaborator}',
    'teams_url': 'https://api.github.com/repos/bleenco/morose/teams',
    'hooks_url': 'https://api.github.com/repos/bleenco/morose/hooks',
    'issue_events_url': 'https://api.github.com/repos/bleenco/morose/issues/events{/number}',
    'events_url': 'https://api.github.com/repos/bleenco/morose/events',
    'assignees_url': 'https://api.github.com/repos/bleenco/morose/assignees{/user}',
    'branches_url': 'https://api.github.com/repos/bleenco/morose/branches{/branch}',
    'tags_url': 'https://api.github.com/repos/bleenco/morose/tags',
    'blobs_url': 'https://api.github.com/repos/bleenco/morose/git/blobs{/sha}',
    'git_tags_url': 'https://api.github.com/repos/bleenco/morose/git/tags{/sha}',
    'git_refs_url': 'https://api.github.com/repos/bleenco/morose/git/refs{/sha}',
    'trees_url': 'https://api.github.com/repos/bleenco/morose/git/trees{/sha}',
    'statuses_url': 'https://api.github.com/repos/bleenco/morose/statuses/{sha}',
    'languages_url': 'https://api.github.com/repos/bleenco/morose/languages',
    'stargazers_url': 'https://api.github.com/repos/bleenco/morose/stargazers',
    'contributors_url': 'https://api.github.com/repos/bleenco/morose/contributors',
    'subscribers_url': 'https://api.github.com/repos/bleenco/morose/subscribers',
    'subscription_url': 'https://api.github.com/repos/bleenco/morose/subscription',
    'commits_url': 'https://api.github.com/repos/bleenco/morose/commits{/sha}',
    'git_commits_url': 'https://api.github.com/repos/bleenco/morose/git/commits{/sha}',
    'comments_url': 'https://api.github.com/repos/bleenco/morose/comments{/number}',
    'issue_comment_url': 'https://api.github.com/repos/bleenco/morose/issues/comments{/number}',
    'contents_url': 'https://api.github.com/repos/bleenco/morose/contents/{+path}',
    'compare_url': 'https://api.github.com/repos/bleenco/morose/compare/{base}...{head}',
    'merges_url': 'https://api.github.com/repos/bleenco/morose/merges',
    'archive_url': 'https://api.github.com/repos/bleenco/morose/{archive_format}{/ref}',
    'downloads_url': 'https://api.github.com/repos/bleenco/morose/downloads',
    'issues_url': 'https://api.github.com/repos/bleenco/morose/issues{/number}',
    'pulls_url': 'https://api.github.com/repos/bleenco/morose/pulls{/number}',
    'milestones_url': 'https://api.github.com/repos/bleenco/morose/milestones{/number}',
    'notifications_url':
      'https://api.github.com/repos/bleenco/morose/notifications{?since,all,participating}',
    'labels_url': 'https://api.github.com/repos/bleenco/morose/labels{/name}',
    'releases_url': 'https://api.github.com/repos/bleenco/morose/releases{/id}',
    'deployments_url': 'https://api.github.com/repos/bleenco/morose/deployments',
    'created_at': '2016-10-29T16:02:28Z',
    'updated_at': '2017-06-23T00:20:33Z',
    'pushed_at': '2017-07-26T08:09:27Z',
    'git_url': 'git://github.com/bleenco/morose.git',
    'ssh_url': 'git@github.com:bleenco/morose.git',
    'clone_url': 'https://github.com/bleenco/morose.git',
    'svn_url': 'https://github.com/bleenco/morose',
    'homepage': 'https://morose.bleenco.io',
    'size': 1990,
    'stargazers_count': 12,
    'watchers_count': 12,
    'language': 'TypeScript',
    'has_issues': true,
    'has_projects': true,
    'has_downloads': true,
    'has_wiki': true,
    'has_pages': false,
    'forks_count': 3,
    'mirror_url': null,
    'open_issues_count': 2,
    'forks': 3,
    'open_issues': 2,
    'watchers': 12,
    'default_branch': 'master'
  },
  'organization': {
    'login': 'bleenco',
    'id': 26046537,
    'url': 'https://api.github.com/orgs/bleenco',
    'repos_url': 'https://api.github.com/orgs/bleenco/repos',
    'events_url': 'https://api.github.com/orgs/bleenco/events',
    'hooks_url': 'https://api.github.com/orgs/bleenco/hooks',
    'issues_url': 'https://api.github.com/orgs/bleenco/issues',
    'members_url': 'https://api.github.com/orgs/bleenco/members{/member}',
    'public_members_url': 'https://api.github.com/orgs/bleenco/public_members{/member}',
    'avatar_url': 'https://avatars2.githubusercontent.com/u/26046537?v=4',
    'description': ''
  },
  'sender': {
    'login': 'Izak88',
    'id': 8555269,
    'avatar_url': 'https://avatars0.githubusercontent.com/u/8555269?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/Izak88',
    'html_url': 'https://github.com/Izak88',
    'followers_url': 'https://api.github.com/users/Izak88/followers',
    'following_url': 'https://api.github.com/users/Izak88/following{/other_user}',
    'gists_url': 'https://api.github.com/users/Izak88/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/Izak88/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/Izak88/subscriptions',
    'organizations_url': 'https://api.github.com/users/Izak88/orgs',
    'repos_url': 'https://api.github.com/users/Izak88/repos',
    'events_url': 'https://api.github.com/users/Izak88/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/Izak88/received_events',
    'type': 'User',
    'site_admin': false
  }
};

export let header = {
  'content-type': 'application/json',
  'X-GitHub-Event': 'status',
  'X-Hub-Signature': 'sha1=b7c49c4f28d64c153ae1ab7f7a8627a1f66a9e55',
  'X-GitHub-Delivery': '61109660-71f6-11e7-9b49-619c5e386bdf'
};
