package webhook

import "time"

type (
	githubPushHook struct {
		Ref        string        `json:"ref"`
		Before     string        `json:"before"`
		After      string        `json:"after"`
		Created    bool          `json:"created"`
		Deleted    bool          `json:"deleted"`
		Forced     bool          `json:"forced"`
		BaseRef    interface{}   `json:"base_ref"`
		Compare    string        `json:"compare"`
		Commits    []interface{} `json:"commits"`
		HeadCommit interface{}   `json:"head_commit"`
		Repository struct {
			ID       int    `json:"id"`
			NodeID   string `json:"node_id"`
			Name     string `json:"name"`
			FullName string `json:"full_name"`
			Private  bool   `json:"private"`
			Owner    struct {
				Name              string `json:"name"`
				Email             string `json:"email"`
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"owner"`
			HTMLURL          string      `json:"html_url"`
			Description      interface{} `json:"description"`
			Fork             bool        `json:"fork"`
			URL              string      `json:"url"`
			ForksURL         string      `json:"forks_url"`
			KeysURL          string      `json:"keys_url"`
			CollaboratorsURL string      `json:"collaborators_url"`
			TeamsURL         string      `json:"teams_url"`
			HooksURL         string      `json:"hooks_url"`
			IssueEventsURL   string      `json:"issue_events_url"`
			EventsURL        string      `json:"events_url"`
			AssigneesURL     string      `json:"assignees_url"`
			BranchesURL      string      `json:"branches_url"`
			TagsURL          string      `json:"tags_url"`
			BlobsURL         string      `json:"blobs_url"`
			GitTagsURL       string      `json:"git_tags_url"`
			GitRefsURL       string      `json:"git_refs_url"`
			TreesURL         string      `json:"trees_url"`
			StatusesURL      string      `json:"statuses_url"`
			LanguagesURL     string      `json:"languages_url"`
			StargazersURL    string      `json:"stargazers_url"`
			ContributorsURL  string      `json:"contributors_url"`
			SubscribersURL   string      `json:"subscribers_url"`
			SubscriptionURL  string      `json:"subscription_url"`
			CommitsURL       string      `json:"commits_url"`
			GitCommitsURL    string      `json:"git_commits_url"`
			CommentsURL      string      `json:"comments_url"`
			IssueCommentURL  string      `json:"issue_comment_url"`
			ContentsURL      string      `json:"contents_url"`
			CompareURL       string      `json:"compare_url"`
			MergesURL        string      `json:"merges_url"`
			ArchiveURL       string      `json:"archive_url"`
			DownloadsURL     string      `json:"downloads_url"`
			IssuesURL        string      `json:"issues_url"`
			PullsURL         string      `json:"pulls_url"`
			MilestonesURL    string      `json:"milestones_url"`
			NotificationsURL string      `json:"notifications_url"`
			LabelsURL        string      `json:"labels_url"`
			ReleasesURL      string      `json:"releases_url"`
			DeploymentsURL   string      `json:"deployments_url"`
			CreatedAt        int         `json:"created_at"`
			UpdatedAt        time.Time   `json:"updated_at"`
			PushedAt         int         `json:"pushed_at"`
			GitURL           string      `json:"git_url"`
			SSHURL           string      `json:"ssh_url"`
			CloneURL         string      `json:"clone_url"`
			SvnURL           string      `json:"svn_url"`
			Homepage         interface{} `json:"homepage"`
			Size             int         `json:"size"`
			StargazersCount  int         `json:"stargazers_count"`
			WatchersCount    int         `json:"watchers_count"`
			Language         string      `json:"language"`
			HasIssues        bool        `json:"has_issues"`
			HasProjects      bool        `json:"has_projects"`
			HasDownloads     bool        `json:"has_downloads"`
			HasWiki          bool        `json:"has_wiki"`
			HasPages         bool        `json:"has_pages"`
			ForksCount       int         `json:"forks_count"`
			MirrorURL        interface{} `json:"mirror_url"`
			Archived         bool        `json:"archived"`
			Disabled         bool        `json:"disabled"`
			OpenIssuesCount  int         `json:"open_issues_count"`
			License          interface{} `json:"license"`
			Forks            int         `json:"forks"`
			OpenIssues       int         `json:"open_issues"`
			Watchers         int         `json:"watchers"`
			DefaultBranch    string      `json:"default_branch"`
			Stargazers       int         `json:"stargazers"`
			MasterBranch     string      `json:"master_branch"`
		} `json:"repository"`
		Pusher struct {
			Name  string `json:"name"`
			Email string `json:"email"`
		} `json:"pusher"`
		Sender struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"sender"`
	}

	githubPullRequestHook struct {
		Action      string `json:"action"`
		Number      int    `json:"number"`
		PullRequest struct {
			URL      string `json:"url"`
			ID       int    `json:"id"`
			NodeID   string `json:"node_id"`
			HTMLURL  string `json:"html_url"`
			DiffURL  string `json:"diff_url"`
			PatchURL string `json:"patch_url"`
			IssueURL string `json:"issue_url"`
			Number   int    `json:"number"`
			State    string `json:"state"`
			Locked   bool   `json:"locked"`
			Title    string `json:"title"`
			User     struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"user"`
			Body               string        `json:"body"`
			CreatedAt          time.Time     `json:"created_at"`
			UpdatedAt          time.Time     `json:"updated_at"`
			ClosedAt           interface{}   `json:"closed_at"`
			MergedAt           interface{}   `json:"merged_at"`
			MergeCommitSha     interface{}   `json:"merge_commit_sha"`
			Assignee           interface{}   `json:"assignee"`
			Assignees          []interface{} `json:"assignees"`
			RequestedReviewers []interface{} `json:"requested_reviewers"`
			RequestedTeams     []interface{} `json:"requested_teams"`
			Labels             []interface{} `json:"labels"`
			Milestone          interface{}   `json:"milestone"`
			CommitsURL         string        `json:"commits_url"`
			ReviewCommentsURL  string        `json:"review_comments_url"`
			ReviewCommentURL   string        `json:"review_comment_url"`
			CommentsURL        string        `json:"comments_url"`
			StatusesURL        string        `json:"statuses_url"`
			Head               struct {
				Label string `json:"label"`
				Ref   string `json:"ref"`
				Sha   string `json:"sha"`
				User  struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"user"`
				Repo struct {
					ID       int    `json:"id"`
					NodeID   string `json:"node_id"`
					Name     string `json:"name"`
					FullName string `json:"full_name"`
					Private  bool   `json:"private"`
					Owner    struct {
						Login             string `json:"login"`
						ID                int    `json:"id"`
						NodeID            string `json:"node_id"`
						AvatarURL         string `json:"avatar_url"`
						GravatarID        string `json:"gravatar_id"`
						URL               string `json:"url"`
						HTMLURL           string `json:"html_url"`
						FollowersURL      string `json:"followers_url"`
						FollowingURL      string `json:"following_url"`
						GistsURL          string `json:"gists_url"`
						StarredURL        string `json:"starred_url"`
						SubscriptionsURL  string `json:"subscriptions_url"`
						OrganizationsURL  string `json:"organizations_url"`
						ReposURL          string `json:"repos_url"`
						EventsURL         string `json:"events_url"`
						ReceivedEventsURL string `json:"received_events_url"`
						Type              string `json:"type"`
						SiteAdmin         bool   `json:"site_admin"`
					} `json:"owner"`
					HTMLURL          string      `json:"html_url"`
					Description      interface{} `json:"description"`
					Fork             bool        `json:"fork"`
					URL              string      `json:"url"`
					ForksURL         string      `json:"forks_url"`
					KeysURL          string      `json:"keys_url"`
					CollaboratorsURL string      `json:"collaborators_url"`
					TeamsURL         string      `json:"teams_url"`
					HooksURL         string      `json:"hooks_url"`
					IssueEventsURL   string      `json:"issue_events_url"`
					EventsURL        string      `json:"events_url"`
					AssigneesURL     string      `json:"assignees_url"`
					BranchesURL      string      `json:"branches_url"`
					TagsURL          string      `json:"tags_url"`
					BlobsURL         string      `json:"blobs_url"`
					GitTagsURL       string      `json:"git_tags_url"`
					GitRefsURL       string      `json:"git_refs_url"`
					TreesURL         string      `json:"trees_url"`
					StatusesURL      string      `json:"statuses_url"`
					LanguagesURL     string      `json:"languages_url"`
					StargazersURL    string      `json:"stargazers_url"`
					ContributorsURL  string      `json:"contributors_url"`
					SubscribersURL   string      `json:"subscribers_url"`
					SubscriptionURL  string      `json:"subscription_url"`
					CommitsURL       string      `json:"commits_url"`
					GitCommitsURL    string      `json:"git_commits_url"`
					CommentsURL      string      `json:"comments_url"`
					IssueCommentURL  string      `json:"issue_comment_url"`
					ContentsURL      string      `json:"contents_url"`
					CompareURL       string      `json:"compare_url"`
					MergesURL        string      `json:"merges_url"`
					ArchiveURL       string      `json:"archive_url"`
					DownloadsURL     string      `json:"downloads_url"`
					IssuesURL        string      `json:"issues_url"`
					PullsURL         string      `json:"pulls_url"`
					MilestonesURL    string      `json:"milestones_url"`
					NotificationsURL string      `json:"notifications_url"`
					LabelsURL        string      `json:"labels_url"`
					ReleasesURL      string      `json:"releases_url"`
					DeploymentsURL   string      `json:"deployments_url"`
					CreatedAt        time.Time   `json:"created_at"`
					UpdatedAt        time.Time   `json:"updated_at"`
					PushedAt         time.Time   `json:"pushed_at"`
					GitURL           string      `json:"git_url"`
					SSHURL           string      `json:"ssh_url"`
					CloneURL         string      `json:"clone_url"`
					SvnURL           string      `json:"svn_url"`
					Homepage         interface{} `json:"homepage"`
					Size             int         `json:"size"`
					StargazersCount  int         `json:"stargazers_count"`
					WatchersCount    int         `json:"watchers_count"`
					Language         interface{} `json:"language"`
					HasIssues        bool        `json:"has_issues"`
					HasProjects      bool        `json:"has_projects"`
					HasDownloads     bool        `json:"has_downloads"`
					HasWiki          bool        `json:"has_wiki"`
					HasPages         bool        `json:"has_pages"`
					ForksCount       int         `json:"forks_count"`
					MirrorURL        interface{} `json:"mirror_url"`
					Archived         bool        `json:"archived"`
					Disabled         bool        `json:"disabled"`
					OpenIssuesCount  int         `json:"open_issues_count"`
					License          interface{} `json:"license"`
					Forks            int         `json:"forks"`
					OpenIssues       int         `json:"open_issues"`
					Watchers         int         `json:"watchers"`
					DefaultBranch    string      `json:"default_branch"`
				} `json:"repo"`
			} `json:"head"`
			Base struct {
				Label string `json:"label"`
				Ref   string `json:"ref"`
				Sha   string `json:"sha"`
				User  struct {
					Login             string `json:"login"`
					ID                int    `json:"id"`
					NodeID            string `json:"node_id"`
					AvatarURL         string `json:"avatar_url"`
					GravatarID        string `json:"gravatar_id"`
					URL               string `json:"url"`
					HTMLURL           string `json:"html_url"`
					FollowersURL      string `json:"followers_url"`
					FollowingURL      string `json:"following_url"`
					GistsURL          string `json:"gists_url"`
					StarredURL        string `json:"starred_url"`
					SubscriptionsURL  string `json:"subscriptions_url"`
					OrganizationsURL  string `json:"organizations_url"`
					ReposURL          string `json:"repos_url"`
					EventsURL         string `json:"events_url"`
					ReceivedEventsURL string `json:"received_events_url"`
					Type              string `json:"type"`
					SiteAdmin         bool   `json:"site_admin"`
				} `json:"user"`
				Repo struct {
					ID       int    `json:"id"`
					NodeID   string `json:"node_id"`
					Name     string `json:"name"`
					FullName string `json:"full_name"`
					Private  bool   `json:"private"`
					Owner    struct {
						Login             string `json:"login"`
						ID                int    `json:"id"`
						NodeID            string `json:"node_id"`
						AvatarURL         string `json:"avatar_url"`
						GravatarID        string `json:"gravatar_id"`
						URL               string `json:"url"`
						HTMLURL           string `json:"html_url"`
						FollowersURL      string `json:"followers_url"`
						FollowingURL      string `json:"following_url"`
						GistsURL          string `json:"gists_url"`
						StarredURL        string `json:"starred_url"`
						SubscriptionsURL  string `json:"subscriptions_url"`
						OrganizationsURL  string `json:"organizations_url"`
						ReposURL          string `json:"repos_url"`
						EventsURL         string `json:"events_url"`
						ReceivedEventsURL string `json:"received_events_url"`
						Type              string `json:"type"`
						SiteAdmin         bool   `json:"site_admin"`
					} `json:"owner"`
					HTMLURL          string      `json:"html_url"`
					Description      interface{} `json:"description"`
					Fork             bool        `json:"fork"`
					URL              string      `json:"url"`
					ForksURL         string      `json:"forks_url"`
					KeysURL          string      `json:"keys_url"`
					CollaboratorsURL string      `json:"collaborators_url"`
					TeamsURL         string      `json:"teams_url"`
					HooksURL         string      `json:"hooks_url"`
					IssueEventsURL   string      `json:"issue_events_url"`
					EventsURL        string      `json:"events_url"`
					AssigneesURL     string      `json:"assignees_url"`
					BranchesURL      string      `json:"branches_url"`
					TagsURL          string      `json:"tags_url"`
					BlobsURL         string      `json:"blobs_url"`
					GitTagsURL       string      `json:"git_tags_url"`
					GitRefsURL       string      `json:"git_refs_url"`
					TreesURL         string      `json:"trees_url"`
					StatusesURL      string      `json:"statuses_url"`
					LanguagesURL     string      `json:"languages_url"`
					StargazersURL    string      `json:"stargazers_url"`
					ContributorsURL  string      `json:"contributors_url"`
					SubscribersURL   string      `json:"subscribers_url"`
					SubscriptionURL  string      `json:"subscription_url"`
					CommitsURL       string      `json:"commits_url"`
					GitCommitsURL    string      `json:"git_commits_url"`
					CommentsURL      string      `json:"comments_url"`
					IssueCommentURL  string      `json:"issue_comment_url"`
					ContentsURL      string      `json:"contents_url"`
					CompareURL       string      `json:"compare_url"`
					MergesURL        string      `json:"merges_url"`
					ArchiveURL       string      `json:"archive_url"`
					DownloadsURL     string      `json:"downloads_url"`
					IssuesURL        string      `json:"issues_url"`
					PullsURL         string      `json:"pulls_url"`
					MilestonesURL    string      `json:"milestones_url"`
					NotificationsURL string      `json:"notifications_url"`
					LabelsURL        string      `json:"labels_url"`
					ReleasesURL      string      `json:"releases_url"`
					DeploymentsURL   string      `json:"deployments_url"`
					CreatedAt        time.Time   `json:"created_at"`
					UpdatedAt        time.Time   `json:"updated_at"`
					PushedAt         time.Time   `json:"pushed_at"`
					GitURL           string      `json:"git_url"`
					SSHURL           string      `json:"ssh_url"`
					CloneURL         string      `json:"clone_url"`
					SvnURL           string      `json:"svn_url"`
					Homepage         interface{} `json:"homepage"`
					Size             int         `json:"size"`
					StargazersCount  int         `json:"stargazers_count"`
					WatchersCount    int         `json:"watchers_count"`
					Language         interface{} `json:"language"`
					HasIssues        bool        `json:"has_issues"`
					HasProjects      bool        `json:"has_projects"`
					HasDownloads     bool        `json:"has_downloads"`
					HasWiki          bool        `json:"has_wiki"`
					HasPages         bool        `json:"has_pages"`
					ForksCount       int         `json:"forks_count"`
					MirrorURL        interface{} `json:"mirror_url"`
					Archived         bool        `json:"archived"`
					Disabled         bool        `json:"disabled"`
					OpenIssuesCount  int         `json:"open_issues_count"`
					License          interface{} `json:"license"`
					Forks            int         `json:"forks"`
					OpenIssues       int         `json:"open_issues"`
					Watchers         int         `json:"watchers"`
					DefaultBranch    string      `json:"default_branch"`
				} `json:"repo"`
			} `json:"base"`
			Links struct {
				Self struct {
					Href string `json:"href"`
				} `json:"self"`
				HTML struct {
					Href string `json:"href"`
				} `json:"html"`
				Issue struct {
					Href string `json:"href"`
				} `json:"issue"`
				Comments struct {
					Href string `json:"href"`
				} `json:"comments"`
				ReviewComments struct {
					Href string `json:"href"`
				} `json:"review_comments"`
				ReviewComment struct {
					Href string `json:"href"`
				} `json:"review_comment"`
				Commits struct {
					Href string `json:"href"`
				} `json:"commits"`
				Statuses struct {
					Href string `json:"href"`
				} `json:"statuses"`
			} `json:"_links"`
			AuthorAssociation   string      `json:"author_association"`
			Draft               bool        `json:"draft"`
			Merged              bool        `json:"merged"`
			Mergeable           interface{} `json:"mergeable"`
			Rebaseable          interface{} `json:"rebaseable"`
			MergeableState      string      `json:"mergeable_state"`
			MergedBy            interface{} `json:"merged_by"`
			Comments            int         `json:"comments"`
			ReviewComments      int         `json:"review_comments"`
			MaintainerCanModify bool        `json:"maintainer_can_modify"`
			Commits             int         `json:"commits"`
			Additions           int         `json:"additions"`
			Deletions           int         `json:"deletions"`
			ChangedFiles        int         `json:"changed_files"`
		} `json:"pull_request"`
		Repository struct {
			ID       int    `json:"id"`
			NodeID   string `json:"node_id"`
			Name     string `json:"name"`
			FullName string `json:"full_name"`
			Private  bool   `json:"private"`
			Owner    struct {
				Login             string `json:"login"`
				ID                int    `json:"id"`
				NodeID            string `json:"node_id"`
				AvatarURL         string `json:"avatar_url"`
				GravatarID        string `json:"gravatar_id"`
				URL               string `json:"url"`
				HTMLURL           string `json:"html_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				OrganizationsURL  string `json:"organizations_url"`
				ReposURL          string `json:"repos_url"`
				EventsURL         string `json:"events_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				Type              string `json:"type"`
				SiteAdmin         bool   `json:"site_admin"`
			} `json:"owner"`
			HTMLURL          string      `json:"html_url"`
			Description      interface{} `json:"description"`
			Fork             bool        `json:"fork"`
			URL              string      `json:"url"`
			ForksURL         string      `json:"forks_url"`
			KeysURL          string      `json:"keys_url"`
			CollaboratorsURL string      `json:"collaborators_url"`
			TeamsURL         string      `json:"teams_url"`
			HooksURL         string      `json:"hooks_url"`
			IssueEventsURL   string      `json:"issue_events_url"`
			EventsURL        string      `json:"events_url"`
			AssigneesURL     string      `json:"assignees_url"`
			BranchesURL      string      `json:"branches_url"`
			TagsURL          string      `json:"tags_url"`
			BlobsURL         string      `json:"blobs_url"`
			GitTagsURL       string      `json:"git_tags_url"`
			GitRefsURL       string      `json:"git_refs_url"`
			TreesURL         string      `json:"trees_url"`
			StatusesURL      string      `json:"statuses_url"`
			LanguagesURL     string      `json:"languages_url"`
			StargazersURL    string      `json:"stargazers_url"`
			ContributorsURL  string      `json:"contributors_url"`
			SubscribersURL   string      `json:"subscribers_url"`
			SubscriptionURL  string      `json:"subscription_url"`
			CommitsURL       string      `json:"commits_url"`
			GitCommitsURL    string      `json:"git_commits_url"`
			CommentsURL      string      `json:"comments_url"`
			IssueCommentURL  string      `json:"issue_comment_url"`
			ContentsURL      string      `json:"contents_url"`
			CompareURL       string      `json:"compare_url"`
			MergesURL        string      `json:"merges_url"`
			ArchiveURL       string      `json:"archive_url"`
			DownloadsURL     string      `json:"downloads_url"`
			IssuesURL        string      `json:"issues_url"`
			PullsURL         string      `json:"pulls_url"`
			MilestonesURL    string      `json:"milestones_url"`
			NotificationsURL string      `json:"notifications_url"`
			LabelsURL        string      `json:"labels_url"`
			ReleasesURL      string      `json:"releases_url"`
			DeploymentsURL   string      `json:"deployments_url"`
			CreatedAt        time.Time   `json:"created_at"`
			UpdatedAt        time.Time   `json:"updated_at"`
			PushedAt         time.Time   `json:"pushed_at"`
			GitURL           string      `json:"git_url"`
			SSHURL           string      `json:"ssh_url"`
			CloneURL         string      `json:"clone_url"`
			SvnURL           string      `json:"svn_url"`
			Homepage         interface{} `json:"homepage"`
			Size             int         `json:"size"`
			StargazersCount  int         `json:"stargazers_count"`
			WatchersCount    int         `json:"watchers_count"`
			Language         interface{} `json:"language"`
			HasIssues        bool        `json:"has_issues"`
			HasProjects      bool        `json:"has_projects"`
			HasDownloads     bool        `json:"has_downloads"`
			HasWiki          bool        `json:"has_wiki"`
			HasPages         bool        `json:"has_pages"`
			ForksCount       int         `json:"forks_count"`
			MirrorURL        interface{} `json:"mirror_url"`
			Archived         bool        `json:"archived"`
			Disabled         bool        `json:"disabled"`
			OpenIssuesCount  int         `json:"open_issues_count"`
			License          interface{} `json:"license"`
			Forks            int         `json:"forks"`
			OpenIssues       int         `json:"open_issues"`
			Watchers         int         `json:"watchers"`
			DefaultBranch    string      `json:"default_branch"`
		} `json:"repository"`
		Sender struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"sender"`
	}

	githubCreateHook struct {
		After      string        `json:"after"`
		BaseRef    string        `json:"base_ref"`
		Before     string        `json:"before"`
		Commits    []interface{} `json:"commits"`
		Compare    string        `json:"compare"`
		Created    bool          `json:"created"`
		Deleted    bool          `json:"deleted"`
		Forced     bool          `json:"forced"`
		HeadCommit struct {
			Added  []string `json:"added"`
			Author struct {
				Email    string `json:"email"`
				Name     string `json:"name"`
				Username string `json:"username"`
			} `json:"author"`
			Committer struct {
				Email    string `json:"email"`
				Name     string `json:"name"`
				Username string `json:"username"`
			} `json:"committer"`
			Distinct  bool          `json:"distinct"`
			ID        string        `json:"id"`
			Message   string        `json:"message"`
			Modified  []interface{} `json:"modified"`
			Removed   []interface{} `json:"removed"`
			Timestamp time.Time     `json:"timestamp"`
			TreeID    string        `json:"tree_id"`
			URL       string        `json:"url"`
		} `json:"head_commit"`
		Pusher struct {
			Email string `json:"email"`
			Name  string `json:"name"`
		} `json:"pusher"`
		Ref        string `json:"ref"`
		Repository struct {
			ArchiveURL       string      `json:"archive_url"`
			Archived         bool        `json:"archived"`
			AssigneesURL     string      `json:"assignees_url"`
			BlobsURL         string      `json:"blobs_url"`
			BranchesURL      string      `json:"branches_url"`
			CloneURL         string      `json:"clone_url"`
			CollaboratorsURL string      `json:"collaborators_url"`
			CommentsURL      string      `json:"comments_url"`
			CommitsURL       string      `json:"commits_url"`
			CompareURL       string      `json:"compare_url"`
			ContentsURL      string      `json:"contents_url"`
			ContributorsURL  string      `json:"contributors_url"`
			CreatedAt        int         `json:"created_at"`
			DefaultBranch    string      `json:"default_branch"`
			DeploymentsURL   string      `json:"deployments_url"`
			Description      string      `json:"description"`
			Disabled         bool        `json:"disabled"`
			DownloadsURL     string      `json:"downloads_url"`
			EventsURL        string      `json:"events_url"`
			Fork             bool        `json:"fork"`
			Forks            int         `json:"forks"`
			ForksCount       int         `json:"forks_count"`
			ForksURL         string      `json:"forks_url"`
			FullName         string      `json:"full_name"`
			GitCommitsURL    string      `json:"git_commits_url"`
			GitRefsURL       string      `json:"git_refs_url"`
			GitTagsURL       string      `json:"git_tags_url"`
			GitURL           string      `json:"git_url"`
			HasDownloads     bool        `json:"has_downloads"`
			HasIssues        bool        `json:"has_issues"`
			HasPages         bool        `json:"has_pages"`
			HasProjects      bool        `json:"has_projects"`
			HasWiki          bool        `json:"has_wiki"`
			Homepage         interface{} `json:"homepage"`
			HooksURL         string      `json:"hooks_url"`
			HTMLURL          string      `json:"html_url"`
			ID               int         `json:"id"`
			IssueCommentURL  string      `json:"issue_comment_url"`
			IssueEventsURL   string      `json:"issue_events_url"`
			IssuesURL        string      `json:"issues_url"`
			KeysURL          string      `json:"keys_url"`
			LabelsURL        string      `json:"labels_url"`
			Language         string      `json:"language"`
			LanguagesURL     string      `json:"languages_url"`
			License          struct {
				Key    string `json:"key"`
				Name   string `json:"name"`
				NodeID string `json:"node_id"`
				SpdxID string `json:"spdx_id"`
				URL    string `json:"url"`
			} `json:"license"`
			MasterBranch     string      `json:"master_branch"`
			MergesURL        string      `json:"merges_url"`
			MilestonesURL    string      `json:"milestones_url"`
			MirrorURL        interface{} `json:"mirror_url"`
			Name             string      `json:"name"`
			NodeID           string      `json:"node_id"`
			NotificationsURL string      `json:"notifications_url"`
			OpenIssues       int         `json:"open_issues"`
			OpenIssuesCount  int         `json:"open_issues_count"`
			Owner            struct {
				AvatarURL         string `json:"avatar_url"`
				Email             string `json:"email"`
				EventsURL         string `json:"events_url"`
				FollowersURL      string `json:"followers_url"`
				FollowingURL      string `json:"following_url"`
				GistsURL          string `json:"gists_url"`
				GravatarID        string `json:"gravatar_id"`
				HTMLURL           string `json:"html_url"`
				ID                int    `json:"id"`
				Login             string `json:"login"`
				Name              string `json:"name"`
				NodeID            string `json:"node_id"`
				OrganizationsURL  string `json:"organizations_url"`
				ReceivedEventsURL string `json:"received_events_url"`
				ReposURL          string `json:"repos_url"`
				SiteAdmin         bool   `json:"site_admin"`
				StarredURL        string `json:"starred_url"`
				SubscriptionsURL  string `json:"subscriptions_url"`
				Type              string `json:"type"`
				URL               string `json:"url"`
			} `json:"owner"`
			Private         bool      `json:"private"`
			PullsURL        string    `json:"pulls_url"`
			PushedAt        int       `json:"pushed_at"`
			ReleasesURL     string    `json:"releases_url"`
			Size            int       `json:"size"`
			SSHURL          string    `json:"ssh_url"`
			Stargazers      int       `json:"stargazers"`
			StargazersCount int       `json:"stargazers_count"`
			StargazersURL   string    `json:"stargazers_url"`
			StatusesURL     string    `json:"statuses_url"`
			SubscribersURL  string    `json:"subscribers_url"`
			SubscriptionURL string    `json:"subscription_url"`
			SvnURL          string    `json:"svn_url"`
			TagsURL         string    `json:"tags_url"`
			TeamsURL        string    `json:"teams_url"`
			TreesURL        string    `json:"trees_url"`
			UpdatedAt       time.Time `json:"updated_at"`
			URL             string    `json:"url"`
			Watchers        int       `json:"watchers"`
			WatchersCount   int       `json:"watchers_count"`
		} `json:"repository"`
		Sender struct {
			AvatarURL         string `json:"avatar_url"`
			EventsURL         string `json:"events_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			GravatarID        string `json:"gravatar_id"`
			HTMLURL           string `json:"html_url"`
			ID                int    `json:"id"`
			Login             string `json:"login"`
			NodeID            string `json:"node_id"`
			OrganizationsURL  string `json:"organizations_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			ReposURL          string `json:"repos_url"`
			SiteAdmin         bool   `json:"site_admin"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			Type              string `json:"type"`
			URL               string `json:"url"`
		} `json:"sender"`
	}
)
