#!/usr/bin/env bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

docker tag $IMAGE_NAME ${repoName}:${tag}
docker push ${repoName}:latest
