version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: abstruse-e2e-postgres
    restart: unless-stopped
    command: -c ssl=on -c ssl_cert_file=/certs/cert.pem  -c ssl_key_file=/certs/key.pem
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=e2etest
      - POSTGRES_DB=abstruse_e2e
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./testdata/postgres:/var/lib/postgresql/data"
      - "./data:/certs/"
    networks:
      e2e_net:
        ipv4_address: 10.20.20.10

  gitea:
    image: gitea/gitea:latest
    container_name: abstruse-e2e-gitea
    restart: unless-stopped
    volumes:
      - "../e2e/data/gitea:/data"
    ports:
      - "3200:3000"
    networks:
      e2e_net:
        ipv4_address: 10.20.20.50

  abstruse-server:
    image: abstruse/abstruse-server:latest
    container_name: abstruse-e2e-server
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "4400:80"
    environment:
      - ABSTRUSE_HTTP_COMPRESS=true
      - ABSTRUSE_DB_DRIVER=postgres
      - ABSTRUSE_DB_HOST=10.20.20.10
      - ABSTRUSE_DB_PORT=5432
      - ABSTRUSE_DB_USER=postgres
      - ABSTRUSE_DB_PASSWORD=e2etest
      - ABSTRUSE_DB_NAME=abstruse_e2e
      - ABSTRUSE_AUTH_JWTSECRET=fa27ef3ef6570e32a79e74deca7c1bc3
      - ABSTRUSE_ETCD_HOST=0.0.0.0
      - ABSTRUSE_ETCD_DATADIR=etcd/
      - ABSTRUSE_ETCD_USERNAME=abstruse
      - ABSTRUSE_ETCD_PASSWORD=235c36984614ec1cbc9f6172a7ba8c9b
      - ABSTRUSE_ETCD_ROOTPASSWORD=1c45154abbf67419b5a20c9258c71775
      - ABSTRUSE_REGISTRY_DATADIR=registry/
      - ABSTRUSE_REGISTRY_USERNAME=abstruse
      - ABSTRUSE_REGISTRY_PASSWORD=fc066d0290bd670fa4f2b38609ebce3d
    volumes:
      - "./testdata/abstruse-server:/abstruse"
    command:
      - "--config=/abstruse/abstruse-server.json"
      - "--log-level=debug"
    networks:
      e2e_net:
        ipv4_address: 10.20.20.20

  abstruse-worker:
    image: abstruse/abstruse-worker:latest
    container_name: abstruse-e2e-worker
    restart: unless-stopped
    depends_on:
      - abstruse-server
    environment:
      - ABSTRUSE_GRPC_LISTENADDR=10.20.20.30:3330
      - ABSTRUSE_ETCD_ADDR=10.20.20.20:2379
      - ABSTRUSE_ETCD_USERNAME=abstruse
      - ABSTRUSE_ETCD_PASSWORD=235c36984614ec1cbc9f6172a7ba8c9b
      - ABSTRUSE_REGISTRY_ADDR=10.20.20.10
      - ABSTRUSE_REGISTRY_USERNAME=abstruse
      - ABSTRUSE_REGISTRY_PASSWORD=fc066d0290bd670fa4f2b38609ebce3d
      - ABSTRUSE_SCHEDULER_MAXPARALLEL=2
      - ABSTRUSE_AUTH_JWTSECRET=fa27ef3ef6570e32a79e74deca7c1bc3
    volumes:
      - "./testdata/abstruse-worker:/abstruse"
      - "/tmp:/tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "--config=/abstruse/abstruse-worker.json"
      - "--log-level=debug"
    networks:
      e2e_net:
        ipv4_address: 10.20.20.30

networks:
  e2e_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
