export let pullRequestOpened = {
  'action': 'opened',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestClosed = {
  'action': 'closed',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'closed',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestReopened = {
  'action': 'reopened',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': null,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestLabeled = {
  'action': 'label_updated',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [
      {
        'id': 1826,
        'name': 'test',
        'color': 'fbca04',
        'url': ''
      }
    ],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestMilestoned = {
  'action': 'milestoned',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [
      {
        'id': 1826,
        'name': 'test',
        'color': 'fbca04',
        'url': ''
      }
    ],
    'milestone': {
      'id': 388,
      'title': 'miletstone1',
      'description': '',
      'state': 'open',
      'open_issues': 1,
      'closed_issues': 0,
      'closed_at': null,
      'due_on': '2017-08-17T00:00:00Z'
    },
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestAssigned = {
  'action': 'assigned',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [
      {
        'id': 1826,
        'name': 'test',
        'color': 'fbca04',
        'url': ''
      }
    ],
    'milestone': {
      'id': 388,
      'title': 'miletstone1',
      'description': '',
      'state': 'open',
      'open_issues': 1,
      'closed_issues': 0,
      'closed_at': null,
      'due_on': '2017-08-17T00:00:00Z'
    },
    'assignee': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestUnassigned = {
  'action': 'unassigned',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [
      {
        'id': 1826,
        'name': 'test',
        'color': 'fbca04',
        'url': ''
      }
    ],
    'milestone': {
      'id': 388,
      'title': 'miletstone1',
      'description': '',
      'state': 'open',
      'open_issues': 1,
      'closed_issues': 0,
      'closed_at': null,
      'due_on': '2017-08-17T00:00:00Z'
    },
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestDemilestoned = {
  'action': 'demilestoned',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [
      {
        'id': 1826,
        'name': 'test',
        'color': 'fbca04',
        'url': ''
      }
    ],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestUnlabeled = {
  'action': 'label_cleared',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test pr',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestEdited = {
  'action': 'edited',
  'number': 2,
  'pull_request': {
    'id': 519,
    'number': 2,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T11:55:09Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/2',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'changes': {
    'title': {
      'from': 'test pr'
    }
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T11:55:09Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let pullRequestSynchronized = {
  'action': 'synchronized',
  'number': 3,
  'pull_request': {
    'id': 520,
    'number': 3,
    'user': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'title': 'test',
    'body': '',
    'labels': [],
    'milestone': null,
    'assignee': null,
    'state': 'open',
    'comments': 0,
    'head_branch': 'testbranch',
    'head_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T12:57:05Z'
    },
    'base_branch': 'master',
    'base_repo': {
      'id': 10335,
      'owner': {
        'id': 15888,
        'login': 'izak88',
        'full_name': '',
        'email': 'izak.lipnik@gmail.com',
        'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
        'username': 'izak88'
      },
      'name': 'test',
      'full_name': 'izak88/test',
      'description': 'test',
      'private': false,
      'fork': false,
      'parent': null,
      'empty': false,
      'mirror': false,
      'size': 12288,
      'html_url': 'https://try.gogs.io/izak88/test',
      'ssh_url': 'git@try.gogs.io:izak88/test.git',
      'clone_url': 'https://try.gogs.io/izak88/test.git',
      'website': '',
      'stars_count': 0,
      'forks_count': 0,
      'watchers_count': 1,
      'open_issues_count': 1,
      'default_branch': 'master',
      'created_at': '2017-08-02T07:14:53Z',
      'updated_at': '2017-08-02T12:57:05Z'
    },
    'html_url': 'https://try.gogs.io/izak88/test/pulls/3',
    'mergeable': true,
    'merged': false,
    'merged_at': null,
    'merge_commit_sha': null,
    'merged_by': null
  },
  'repository': {
    'id': 10335,
    'owner': {
      'id': 15888,
      'login': 'izak88',
      'full_name': '',
      'email': 'izak.lipnik@gmail.com',
      'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
      'username': 'izak88'
    },
    'name': 'test',
    'full_name': 'izak88/test',
    'description': 'test',
    'private': false,
    'fork': false,
    'parent': null,
    'empty': false,
    'mirror': false,
    'size': 12288,
    'html_url': 'https://try.gogs.io/izak88/test',
    'ssh_url': 'git@try.gogs.io:izak88/test.git',
    'clone_url': 'https://try.gogs.io/izak88/test.git',
    'website': '',
    'stars_count': 0,
    'forks_count': 0,
    'watchers_count': 1,
    'open_issues_count': 1,
    'default_branch': 'master',
    'created_at': '2017-08-02T07:14:53Z',
    'updated_at': '2017-08-02T12:57:05Z'
  },
  'sender': {
    'id': 15888,
    'login': 'izak88',
    'full_name': '',
    'email': 'izak.lipnik@gmail.com',
    'avatar_url': 'https://secure.gravatar.com/avatar/c27a4cf56134b3956555fc8e1d7cced0',
    'username': 'izak88'
  }
};

export let header = {
  'Content-Type': 'application/json',
  'X-Gogs-Delivery': 'c5c8ee50-20fc-4545-a4f4-b272f8a3afc0',
  'X-Gogs-Event': 'pull_request',
  'X-Gogs-Signature': '6bd4b34f02c78656ed58e1b7d16155357d5f389f37b7346de4f52acc6fb54b70'
};
